INSERT INTO AGENDAMIENTO (FECHA_GESTION,AÑO_GESTION ,MES_GESTION ,DIA_GESTION,HORA_GESTION,USUARIO,CANAL_INGRESO ,CUENTA,ORDEN ,RANGO_DIAS,COMUNIDAD,NODO,REPORTE_ALIADO,VECES_PROGRAMADA,GESTION,FECHA_AGENDA,OBSERVACIONES)VALUES()

INSERT INTO CONSOLIDADO(ID_GESTION,CUENTA,CANAL_INGRESO,PROCESO,GESTION,SUB_RAZON,SERVICIOS_DX,FECHA_GESTION,AÑO_GESTION,MES_GESTION,DIA_GESTION,HORA_GESTION) VALUES()

INSERT INTO PRODUCTIVIDAD (USUARIO,ID_GESTION,FECHA,AÑO,MES,DIA,HORA_GESTION,CUENTA,PROCESO,PORCENTAJE)VALUES()

SELECT * FROM AGENDAMIENTO WHERE CUENTA=0 AND ORDEN=0

UPDATE AGENDAMIENTO SET CUENTA=, ORDEN=,RANGO_DIAS=, COMUNIDAD=,NODO=,REPORTE_ALIADO=,VECES_PROGRAMADA=,GESTION=,FECHA_AGENDA=, OBSERVACIONES=
